project_id = "kfxalpvbtbvkncztjwzc"

[functions.envoyer-commande]
verify_jwt = false

[functions.envoyer-inscription]
verify_jwt = true

[functions.embellir-photo-produit]
verify_jwt = true

[functions.nettoyer-originaux-images]
verify_jwt = true
