project_id = "kfxalpvbtbvkncztjwzc"

[functions.envoyer-commande]
verify_jwt = false

[functions.envoyer-inscription]
verify_jwt = true

[functions.analyser-article-gemini]
verify_jwt = true

[functions.analyser-article-groq]
verify_jwt = true

[functions.analyser-article-openrouter]
verify_jwt = true
