-- Nommage public plus cohérent pour le lot de montres identifié visuellement.
-- Les caractéristiques utilisées sont limitées aux couleurs, formes et cadrans visibles.
UPDATE public.produits AS p
SET nom = v.nom
FROM (VALUES
  (155, 'Montre Squelette Bleu Acier'),
  (156, 'Montre Marine Bracelet Acier'),
  (157, 'Montre Squelette Graphite'),
  (158, 'Montre Bordeaux Bracelet Acier'),
  (159, 'Montre Squelette Argent'),
  (160, 'Montre Chronographe Bleu Nuit'),
  (161, 'Montre Or Noir Élégance'),
  (162, 'Montre Chronographe Bleu Royal'),
  (163, 'Montre Rose Poudré'),
  (164, 'Montre Rectangle Argent'),
  (165, 'Montre Rectangle Cuir Brun'),
  (166, 'Montre Chronographe Rouge Or'),
  (167, 'Montre Minimaliste Bleu Ardoise'),
  (168, 'Montre Sport Blanche'),
  (169, 'Montre Squelette Noir Argent'),
  (170, 'Montre Noire Chiffres Romains'),
  (171, 'Montre Carrée Bleu Cristal'),
  (172, 'Montre Carrée Ambre Cristal'),
  (173, 'Montre Carrée Rouge Cristal'),
  (174, 'Montre Rectangle Classique'),
  (175, 'Montre Squelette Or'),
  (176, 'Montre Classique Ivoire'),
  (177, 'Montre Rectangle Or Brun'),
  (178, 'Montre Squelette Rose Cuivré'),
  (179, 'Montre Carrée Carbone'),
  (180, 'Montre Sport Bleu Nuit'),
  (181, 'Montre Chronographe Or Bleu'),
  (182, 'Montre Cristal Argent'),
  (183, 'Montre Chronographe Bordeaux'),
  (184, 'Montre Carrée Carbone Bleu'),
  (185, 'Montre Bleu Nuit Signature'),
  (186, 'Montre Digitale Sport Noire'),
  (187, 'Montre Carrée Cuir Noir'),
  (188, 'Montre Classique Ivoire Cuir'),
  (189, 'Montre Rectangle Graphite'),
  (190, 'Montre Bleu Saphir'),
  (191, 'Montre Chronographe Carbone'),
  (192, 'Montre Perle Argent'),
  (193, 'Montre Perle Dorée'),
  (194, 'Montre Chronographe Or Noir'),
  (195, 'Montre Bleu Acier'),
  (196, 'Montre Squelette Carbone'),
  (197, 'Montre Squelette Rosé'),
  (198, 'Montre Bicolore Champagne'),
  (199, 'Montre Argent Lumière'),
  (200, 'Montre Sport Olive'),
  (201, 'Montre Sport Graphite'),
  (202, 'Montre Digitale Carbone'),
  (203, 'Montre Carrée Acier'),
  (204, 'Montre Émeraude Noire'),
  (205, 'Montre Squelette Noir')
) AS v(id, nom)
WHERE p.id = v.id
  AND p.categorie_id = 'mode'
  AND p.sous_categorie_id = 'bijoux';
