begin;

create table if not exists public.site_visites (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  visit_day date not null,
  visitor_hash text not null,
  path text not null default '/',
  constraint site_visites_path_length check (char_length(path) between 1 and 200),
  constraint site_visites_hash_length check (char_length(visitor_hash) between 32 and 128)
);

create index if not exists site_visites_day_hash_idx
  on public.site_visites (visit_day, visitor_hash);
create index if not exists site_visites_created_at_idx
  on public.site_visites (created_at);

alter table public.site_visites enable row level security;
revoke all on table public.site_visites from anon, authenticated;

comment on table public.site_visites is
  'Événements de visite sans identifiant brut : visitor_hash est un HMAC journalier non réversible côté navigateur.';
comment on column public.site_visites.visitor_hash is
  'Hachage HMAC du visiteur et du jour, calculé côté Edge Function avec un secret serveur.';

commit;
