begin;

create table if not exists public.traitements_images_produits (
  id bigint generated by default as identity primary key,
  produit_id bigint not null references public.produits(id) on delete cascade,
  source_image_url text not null,
  optimized_image_url text,
  status text not null default 'en_attente' check (status in ('en_attente', 'en_traitement', 'termine', 'echec', 'obsolete')),
  attempts integer not null default 0 check (attempts >= 0 and attempts <= 3),
  next_attempt_at timestamptz not null default now(),
  started_at timestamptz,
  finished_at timestamptz,
  last_error text,
  created_at timestamptz not null default now(),
  unique (produit_id, source_image_url)
);

create index if not exists traitements_images_produits_pending_idx
  on public.traitements_images_produits (status, next_attempt_at, created_at);

alter table public.traitements_images_produits enable row level security;
revoke all on table public.traitements_images_produits from anon, authenticated;

grant usage, select on sequence public.traitements_images_produits_id_seq to service_role;
grant select, insert, update, delete on table public.traitements_images_produits to service_role;

create or replace function public.ajouter_file_image_produit()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.image_url is null or btrim(new.image_url) = '' then
    return new;
  end if;

  -- Seules les photos du bucket public autorisé sont traitées.
  -- Une sortie déjà optimisée ne recrée pas une boucle de file.
  if new.image_url not like 'https://kfxalpvbtbvkncztjwzc.supabase.co/storage/v1/object/public/photos-articles/%'
     or new.image_url like '%/optimized/%' then
    return new;
  end if;

  insert into public.traitements_images_produits (produit_id, source_image_url)
  values (new.id, new.image_url)
  on conflict (produit_id, source_image_url) do nothing;

  return new;
end;
$$;

revoke all on function public.ajouter_file_image_produit() from public, anon, authenticated;
grant execute on function public.ajouter_file_image_produit() to service_role;

drop trigger if exists produits_queue_image_optimization on public.produits;
create trigger produits_queue_image_optimization
after insert or update of image_url on public.produits
for each row execute function public.ajouter_file_image_produit();

-- Recrée le job de façon idempotente. La clé utilisée est la clé publishable
-- déjà prévue pour les appels publics ; aucun secret service_role n’est exposé.
do $$
begin
  perform cron.unschedule('embellir-images-produits');
exception
  when others then null;
end $$;

select cron.schedule(
  'embellir-images-produits',
  '* * * * *',
  $$
    select net.http_post(
      url := 'https://kfxalpvbtbvkncztjwzc.supabase.co/functions/v1/embellir-photo-produit',
      headers := jsonb_build_object(
        'Content-Type', 'application/json',
        'apikey', 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmeWFscHZidGJ2a25jenRqd3pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQxNTE2MDgsImV4cCI6MjA5OTcyNzYwOH0.bO1aExLXi1XTCNPMe98h0BFZrOHSM_bII_4WFX5ZPpg',
        'Authorization', 'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtmeGFscHZidGJ2a25jenRqd3pjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODQxNTE2MDgsImV4cCI6MjA5OTcyNzYwOH0.bO1aExLXi1XTCNPMe98h0BFZrOHSM_bII_4WFX5ZPpg'
      ),
      body := '{}'::jsonb
    );
  $$
);

commit;
